In [1]:
import numpy as np

In [ ]:
# NumPy의 주요한 객체는 다차원의 동종 어레이 (homogeneous multidimensional array)입니다.
# 보통 숫자로 구성되는 어레이는 모두 동일한 타입의 요소를 갖고, 음이 아닌 정수 (0, 1, 2 ..)로 인덱싱됩니다.
# NumPy에서 차원은 축 (axis)이라고 합니다.

In [ ]:
'''
numpy.ndarray 객체의 중요한 속성은 다음과 같습니다:

ndarray.ndim  
: 어레이의 축의 개수 (차원).  
ndarray.shape  
: 어레이의 차원. 각 차원의 어레이의 크기를 나타내는 정수의 튜플.  
n개의 행, m개의 열을 갖는 행렬의 경우, shape은 (n, m). 따라서 shape 튜플의 길이는 축의 개수가 됨.  
ndarray.size  
: 어레이의 요수의 총 개수. shape 튜플의 요소의 곱과 같음.  
ndarray.dtype  
: 어레이의 요소의 타입을 나타내는 객체.  
표준 파이썬 타입을 이용해서 dtype을 만들거나 지정할 수 있다.  
이 외에도 NumPy는 numpy.int32, numpy.int16, numpy.float64와 같은 고유한 타입을 제공함.  
ndarray.itemsize  
: 어레이의 각 요소의 바이트 크기.  
예를 들어, float64 타입의 요소를 갖는 어레이는 itemsize가 8 (=64/8).  
complex32 타입을 갖는 어레이의 itemsize는 4 (=32/8). ndarray.dtype.itemsize와 같음.  
ndarray.data
: 어레이의 실제 요소를 갖는 버퍼.  
보통, 인덱스 기능을 이용해서 어레이의 요소에 접근하기 때문에 이 속성을 사용할 필요가 없을 것임.
'''  

In [2]:
a = np.arange(15).reshape(3, 5)
print(a)
print('a.shape:', a.shape)             # 어레이의 차원
print('a.ndim:', a.ndim)               # 어레이의 축의 개수
print('a.dtype.name:', a.dtype.name)   # 어레이 요소의 타입
print('a.itemsize:', a.itemsize)       # 어레이 요소의 바이트 크기
print('a.size:', a.size)               # 어레이 요소의 총 개수
print('type(a):', type(a))             # 어레이의 타입

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a.shape: (3, 5)
a.ndim: 2
a.dtype.name: int32
a.itemsize: 4
a.size: 15
type(a): <class 'numpy.ndarray'>


#### np.array() 사용하기
- 파이썬 리스트 또는 튜플을 np.array()에 입력하면 NumPy 어레이가 만들어집니다.

In [3]:
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)

b = np.array([1.2, 3.5, 5.1])
print(b)
print(type(b))
print(b.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int32
[1.2 3.5 5.1]
<class 'numpy.ndarray'>
float64


#### 타입 지정하기 (dtype)

In [4]:
a = np.array([[1,2], [3,4]], dtype=complex)
print(a)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


#### np.zeros(), np.ones(), np.empty() 사용하기

In [5]:
a = np.zeros(10)
print(a)

b = np.ones((2, 3, 4), dtype=np.int16)
print(b)

c = np.empty((2, 3))
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[0. 0. 0.]
 [0. 0. 0.]]


#### np.arange() 사용하기
- 연속적인 숫자들을 만들어내기 위해 NumPy는 파이썬의 range()와 유사한 함수인 np.arange()를 제공하는데,
- np.arange()는 리스트 대신 어레이를 반환합니다.

#### np.linspace() 사용하기
- np.arange()를 부동소수점 인수와 함께 사용할 때,

- 부동소수점 정밀도의 제한 때문에 일반적으로 요소의 개수를 예측하기 어렵습니다.

- 이런 이유로 증가폭 (step) 대신 요소의 개수를 인수로 입력하는 np.linspace() 함수를 사용하는 것이 좋습니다.


####1, 2, 3차원 어레이 출력하기


In [7]:
a = np.arange(6)                         # 1d array
print(a)

b = np.arange(12).reshape(4,3)           # 2d array
print(b)

c = np.arange(24).reshape(2,3,4)         # 3d array

[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
