In [ ]:
# numpy : 대량의 데이터를 처리하기 위해서(배열이 구현되어 있는 패키지)
# -> 수치연산(벡터, 행렬연산)
# 넘파이 배열은 속도가 빠름, 적은 메모리 차지, 같은 자료형, 원소의 개수 변경 불가
# 리스트는 속도가 느림, 메모리 차지 많음, 자료형이 달라도 됨, 원소의 개수가 변경 가능
# 파이썬은 자체적으로 배열을 제공하지 않는다.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
np.array([1,2,3,4]) # array함수에 리스트를 넣음, 1차원 배열
type(np.array([1,2,3,4])) # ndarray 자료형의 구조

numpy.ndarray

In [ ]:
# 벡터화연산 : 배열의 각 원소에 대한 반복 연산을 명령어 1개로 처리
# 
# [1,2,3,4] -> [2,3,4,5] : 파이썬의 경우 4번 연산
# [1,2,3,4] -> [2,3,4,5] : 넘파이의 경우 1번 연산

In [6]:
#파이썬의 연산
data=[1,2,3,4]
ans=[i+1 for i in data]
ans
    

[2, 3, 4, 5]

In [9]:
#넘파이 연산
np.array(data)
np.array(data)+1

array([2, 3, 4, 5])

In [10]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [17]:
x+y #요소간 곱셈 
2*x+y
x ==y #각각의 요소끼리 비교
x > 2
y>4
(x>2) & (y>4) # & : and연산

array([False, False,  True])

In [ ]:
# 브로드캐스팅 : 손오공

In [20]:
# 1차원 배열 : 벡터
# 2차원 배열 : 행렬 (리스트의 리스트를 array에 넣으면 행렬이 된다.)

x=np.array([[1,2,3],
[4,5,6]]) #행이 두개 있다. 열이 3개 # 2*3배열 

In [22]:
len(x) # 행의 개수
len(x[0]) #열의 개수

3

In [23]:
[[1,2,3], [1,2,3], [1,2,3]]

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [26]:
x=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
# 가장 바깥쪽에서 요소는 2개
# x배열의 깊이 : 2
# x배열의 행(그 다음 요소개수) : 2
# x배열의 열(가장 안쪽에 있는 데이터 개수): 3
# x : 2*3*4배열

In [27]:
x

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [33]:
x=np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
# 2*3*4
# x배열의 깊이 : 2
# x배열의 행 : 3 
# x배열의 열 : 4
# x배열의 shape? 2*3*4배열


# 3차원배열x = [행렬1, 행렬2]
# x[0]=행렬1
# x[1]=행렬2
# x[0][0]=행렬1의 첫번째 행 

len(x) #깊이
len(x[0]) #행
len(x[0][0]) #열

4

In [38]:
x.ndim # 배열의 차원 확인 # n차원에서 n구하기
x.shape #shape(배열의 크기)
type(x.shape)

tuple

In [12]:
x=np.array([1,2,3])

In [46]:
# axis : 축 (axes의 복수)
x[-1]

3

In [ ]:
# 코딩공부는 손으로 한다.

In [13]:
x=np.array([[1,2,3], [4,5,6]])
x
x[0] #첫번째 행 출력
x[1]
x[-1] #마지막행으로부터 거꾸로 참조
x[-2]

x[0][0] #첫번째 행의 첫번째 열 출력
x[-2][0]
x[-2][-3]
x[0,0] #컴마를 이용한 접근도 가능. 컴마로 구분된 차원을 축(axis)라고 함

1

In [20]:
x=np.array([[1,2,3], [4,5,6]])
#x[행, 열]
x[0] #첫번째 행 전체
x[0,] #첫번째 행 전체
x[0, :] #첫번째 행 전체

x[1]
x[1, :]

x[:,1] # :는 전체를 의미 

array([2, 5])

In [37]:
x[-1][-2:]
x[1,1:]
x[1,1:3]
x[-1,-2:]

array([5, 6])

In [40]:
x[:,1:] #x[행,열] # 시작인덱스:끝인덱스(끝은 포함안됨)

array([[2, 3],
       [5, 6]])

In [ ]:
#불린참조, 불린값(True/False)으로 구성된 배열로 참조,
# 주의 : 참조 대상 배열(x)와 불린 배열(b)의 크기가 동일

In [3]:
x=np.array([1,2,3])
b=np.array([True,False,True])

In [4]:
x[b]

array([1, 3])

In [6]:
x>1
x[x>1]

array([2, 3])

In [10]:
x=np.array([1,2,3])
# b=np.array([True,False,True,True])
#b=np.array([True,False,True])
x%2==1

array([ True, False,  True])

In [11]:
x[x%2==1]

array([1, 3])

In [12]:
x=np.array([10,20,30,40,50])
y=np.array([0,2,4,0,0,2])

In [13]:
#정수 배열 인덱싱 
x[y]

array([10, 30, 50, 10, 10, 30])

In [14]:
x=np.array([[10,20,30],[40,50,60]])

In [18]:
x[ :, [True,False,True]] # 0번 2번 index 열 데이터 추출
x[[True,False],:]

array([[10, 20, 30]])

In [19]:
x[:]

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
x[ : , [0,2]]
x[ : , [2,0]]
x[ : , [2,0,0,2,0]]
x[[1,1,1,0],:]
x[[1,0],:]

array([[40, 50, 60],
       [10, 20, 30]])

In [41]:
x=np.array([[0, 1, 2, 3, 4],
[5,6,7,8,9],
[10,11,12,13,14]])

In [42]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [60]:
# 7참조
x[1,2]
x[x==7]
# 14참조
x[-1][-1]
#[6,7]참조
x[1][1:3]
#[7,12]참조
x[1:,2]
x[(x==6)|(x==7)]
#[[3,4],[8,9]]
x[:2,3:]

array([[3, 4],
       [8, 9]])

In [61]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])


In [69]:
# 3의 배수 출력
x[x%3==0]
# 4로 나누었을때 나머지가 1인 값을 출력 
x[x%4==1]
# 3으로 나누어지고 4로 나누면 나머지가 1인 값을 출력 
x[((x%3==0) & (x%4==1))]

array([9])

In [74]:
x=np.array([1,2.5])

In [75]:
type(x)
# 배열에 저장된 자료 타입을 확인
# dtype(=data type)
x.dtype

dtype('float64')

In [77]:
x=np.array([1,2], dtype='f') #dtype:f :실수
x.dtype
x

array([1., 2.], dtype=float32)

In [ ]:
inf #infinity, Nan (not a number)

In [79]:
np.inf #무한대를 표현하는 상수
np.nan #정의할 수 없는 숫자

nan

In [87]:
print(np.array([1]) / np.array([0])) #inf
print(np.array([0]) / np.array([1])) #0
print(np.array([-1]) / np.array([0])) #inf
print(np.array([0]) / np.array([0])) #NaN

print(np.log(0))
print(np.exp(-np.inf))


[inf]
[0.]
[-inf]
[nan]
-inf
0.0


<ipython-input-87-c870cdd381ce>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([1]) / np.array([0])) #inf
<ipython-input-87-c870cdd381ce>:3: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([-1]) / np.array([0])) #inf
<ipython-input-87-c870cdd381ce>:4: RuntimeWarning: invalid value encountered in true_divide
  print(np.array([0]) / np.array([0])) #NaN
<ipython-input-87-c870cdd381ce>:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


In [88]:
np.zeros(3)

array([0., 0., 0.])

In [90]:
np.zeros((3,2))
np.zeros((3,2,4)) #(깊이, 행,열)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [91]:
np.zeros((3,2,4), dtype='i') # i=integer 정수

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [93]:
np.ones((3,2,4))*2

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [95]:
x=np.ones((3,2,4)) ; x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [98]:
# zeros(ones)_like함수 : x배열의 크기와 동일하게 0 또는 1로 모두 초기화하여 생성
y=np.zeros_like(x);y
y=np.ones_like(x, dtype='i');y

#np.ones_like(x, dtype='i') 작업을 하면 컴퓨터 내부에서는 어떤 일이?
#x배열 크기 확인 -> x배열 크기와 동일한 배열 공간 생성 -> 1로 모두 초기화


array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [99]:
np.empty((3,2)) #배열만 빠르게 만든다.
#zeros:0으로 초기화, empty : 기존에 메모리에 남아있는 쓰게기값으로 초기화

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [103]:
np.array(list(range(8)))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [104]:
np.array(list(range(8))).reshape(4,2) #shape를 4행 2열로 재정의

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [108]:
np.arange(8) #np.array(list(range(8)))
# arange와 range 모두 범위를 만드는 객체 
# arange는 넘파이 함수, range는 리스트 함수
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [110]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [111]:
np.linspace(0, 100, 10) #선형 구간, 시작, 끝, 개수 #구간을 나눠 생성

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [115]:
# np.logspace(시작, 끝, 개수, base) 
#로그 스케일 값으로 배열 생성
np.logspace(start=1,stop=10,num=10)
np.logspace(start=1,stop=10,num=10, base=10)
np.logspace(start=1,stop=10,num=10, base=2) #base가 2

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [116]:
#전치행렬 : 행과 열을 바꾸어놓은 행렬, T속성을 이용

In [120]:
# 1~6가지 2행 3열 행렬생성
X=np.arange(1,7).reshape(2,3);X

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
X.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
# 엘리먼트 와이즈 프로덕
# element wise product : 요소간 곱셈 연산

# 닷 프로덕, 매트릭스 멀티플라이(행렬의 곱셈)
# dot product, matrix mutliply

In [123]:
x=np.arange(12).reshape(3,4);x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [125]:
x=np.arange(12).reshape(3,-1);x # 행은 3을 알겠는데 열은 모르겠다 -> -1로 한다.
x=np.arange(12).reshape(-1,2);x # 열은 2개, 행은 네가 계산해서 알아서 해


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [129]:
x=np.arange(24);x
x.reshape(2,3,-1)
x.reshape(2,-1,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
# reshape으로 차원을 증가시킬 수 있다
# ex) reshape함수 : 1차원 배열 -> 다차원 배열로 변환 가능

# ex) flatten함수 또는 ravel함수 : 다차원 배열 -> 1차원 배열로 변환 가능 (평평하다)


In [134]:
x=x.reshape(2,3,-1);x
x.shape
x.ndim

3

In [138]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [136]:
x.ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [139]:
import pandas as pd

In [153]:
df=pd.read_csv('e:/data/samsung.csv');df

Open   High    Low  Close    Adj Close    Volume
0    57000  58800  56400  58600  56560.60547  48431566
1    60300  60400  58600  59000  56946.68750  36476611
2    59700  60100  59000  59000  56946.68750  19285354
3    59500  59600  57700  57900  55884.96875  21943345
4    57800  57900  56700  56800  54823.25000  21158940
..     ...    ...    ...    ...          ...       ...
244  79000  79800  78900  79700  79700.00000  12618790
245  79700  79900  79200  79300  79300.00000   9098910
246  79400  79500  78800  78800  78800.00000  10040975
247  79200  79400  78500  78500  78500.00000  11427693
248  78300  78900  78100  78300  78300.00000  10191446

[249 rows x 6 columns]

In [155]:
samsung = np.loadtxt('e:/data/samsung.csv', skiprows=1, delimiter=',') #첫번째 줄 스킵 
samsung

#samsung 변수에 담긴 배열을 이용하여 오늘 학습한 함수, 열, 행 추출

array([[   57000.     ,    58800.     ,    56400.     ,    58600.     ,
           56560.60547, 48431566.     ],
       [   60300.     ,    60400.     ,    58600.     ,    59000.     ,
           56946.6875 , 36476611.     ],
       [   59700.     ,    60100.     ,    59000.     ,    59000.     ,
           56946.6875 , 19285354.     ],
       ...,
       [   79400.     ,    79500.     ,    78800.     ,    78800.     ,
           78800.     , 10040975.     ],
       [   79200.     ,    79400.     ,    78500.     ,    78500.     ,
           78500.     , 11427693.     ],
       [   78300.     ,    78900.     ,    78100.     ,    78300.     ,
           78300.     , 10191446.     ]])