In [130]:
import numpy as np
import pandas as pd

# Jupyter Notebook의 출력을 소수점 이하 3자리로 제한
%precision 3
# Dataframe의 출력을 소수점 이하 3자리로 제한
pd.set_option('precision', 3)

In [46]:
# 벡터 : 크기 + 방향 
# 벡터의 크기와 방향은 좌표축 성분으로 나누어 표현

# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
arr = np.arange(30.).reshape(5, -1)
print(arr)
# 전체의 최댓값
print(arr.max())
# 각 행의 합
print(arr.sum(axis=1))
# 각 행의 최댓값
print(arr.max(axis=1))
# 각 열의 평균
print(arr.mean(axis=0))
# 각 열의 최솟값
print(arr.min(axis=0))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]]
29.0
[ 15.  51.  87. 123. 159.]
[ 5. 11. 17. 23. 29.]
[12. 13. 14. 15. 16. 17.]
[0. 1. 2. 3. 4. 5.]


In [48]:
arr = np.arange(30.).reshape(5, -1);arr

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]])

In [49]:
#정렬: axis=0 -> 행을 정렬, axis=1 -> 열을 정렬

In [53]:
arr=np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])


In [58]:
arr.sort(axis=1) ;arr # 행 기준

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [59]:
arr.sort(axis=0) ;arr # 열 기준 #inplace : 값이 자체적으로 바뀜(sort)

array([[ 1,  2,  5,  7],
       [ 1,  4, 11, 12],
       [ 3,  9, 14, 15]])

In [60]:
x=np.argsort([40,30,10,20 ]) # 정렬된 인덱스 값 반환
x

array([2, 3, 1, 0], dtype=int64)

In [61]:
data = [70, 91, 69, 78, 82]

In [64]:
# 기술통계
len(data)
sum(data)/len(data) # 산술통계
np.mean(data)

78.0

In [ ]:
# 분산? 데이터와 평균값 사이의 거리에 대한 제곱의 평균
# 분산이 작다? 데이터가 모여 있다

In [91]:
# def myVar(data):
    # dataVar = [((data[i] - (sum(data)/len(data)))/(len(data)-1))**2  for i in range(len(data))]
    # return dataVar

# def myStd(data):
    # dataStd = [np.sqrt(myVar(data)[i]) for i in range(len(data))]
    # return dataStd

In [103]:
data = [70, 91, 69, 78, 82]

In [102]:
np.var(data)
np.std(data)

8.12403840463596

In [104]:
np.median(data)

78.0

In [105]:
#사분위수 : 데이터를 오름차순 정렬
# 1사분위수 : 1/4 위치(하위 25%)에 있는 수 
# 2사분위수 : 2/4 위치(median)에 있는 수 
# 3사분위수 : 3/4 위치(상위 25%)에 있는 수 
# 최대값 (4/4 위치)

In [102]:
np.var(data)
np.std(data)

8.12403840463596

In [124]:
np.random.seed(802) 

In [127]:
# seed: 씨앗 # 동일한 씨앗을 줬기 때문에 동일한 열매를 준다.
# np.random.rand: 0~1 난수를 생성해준다.
# np.random.randn: 표준정규분포 난수를 생성해준다. (n : normal distribution, 평균:0, 표준편차:1)
# np.random.randint: 정수 난수 생성

np.random.randint(1, 10, 5) # 1~10까지 5개의 난수 생성
# 1<=난수<10

array([4, 9, 5, 3, 1])

In [132]:
# 표준편차가 30 -> 평균과 차이가 크다.
# 단위를 고려
x=[173, 181, 168, 175, 179]
y=[1.73,1.81, 1.68, 1.75, 1.79]
np.var(x) #분산이 20.96
np.var(y) #분산이 0.002

0.0020960000000000037

In [134]:
# 머신너링할 때 데이터의 단위가 다른 것이 뒤섞여 있는 경우가 있다.
# 표준값(Z값) = (데이터 - 평균) / 표준편차 => 비교가 가능

In [137]:
x = np.random.randint(1,100, 30)
x

array([33, 27, 91, 75, 75, 98, 61, 60, 85, 61, 22, 49, 77, 96, 22, 74, 45,
       83, 84,  9,  9, 12,  4, 21, 32, 86, 99, 69,  2, 30])

In [145]:
np.percentile(x, 25) #percentile:백분위수
np.percentile(x, 50) #percentile:백분위수
np.percentile(x, 75) #percentile:백분위수
np.percentile(x, 100) #percentile:백분위수

99.0

In [152]:
np.random.randint(10,20,size=(3,5))

array([[10, 16, 16, 16, 16],
       [16, 11, 12, 12, 18],
       [19, 12, 13, 10, 10]])

In [154]:
np.unique([1,1,2,2,3])

array([1, 2, 3])

In [159]:
a, b=np.unique([1,1,2,2,3], return_counts=True) # 1이 2개있다. 2가 2개있다. 3개가 1이 있다.
print(a, b)

[1 2 3] [2 2 1]


In [166]:
np.bincount([1,1,2,2,3]) #0부터 3까지 각 수에 대한 카운트 값

#주사위
np.bincount([1,1,2,2,3], minlength=6) # 0부터 8까지 각 몇개 나왔냐
# 0번은 버림

array([0, 2, 2, 1, 0, 0], dtype=int64)