In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
data = {'key1':['a', 'b', 'b', 'c', 'c'],
'key2':['v', 'w', 'w', 'w', 'y'],
'col':[1, 2, 2, 2, 5]}

In [19]:
df=pd.DataFrame(data, columns=data.keys())
df

key1 key2  col
0    a    v    1
1    b    w    2
2    b    w    2
3    c    w    2
4    c    y    5

In [20]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [21]:
df.duplicated(['key1'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [22]:
df.duplicated(['key1', 'key2'])

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [24]:
df.drop_duplicates(['key1'], keep='first') # default

key1 key2  col
0    a    v    1
1    b    w    2
3    c    w    2

In [25]:
df.drop_duplicates(['key1'], keep='last')

key1 key2  col
0    a    v    1
2    b    w    2
4    c    y    5

In [28]:
# numpy.triu() : 상삼각행렬 리턴 

# 1~9까지의 값이 3*3행렬
arr=np.array(np.arange(1,10).reshape(3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.triu(ary)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [30]:
np.triu(ary, 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [31]:
np.triu(ary, -1)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 8, 9]])