In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [ ]:
#1. 다중선형회귀모델

In [2]:
tf.set_random_seed(777)
x1_data = [73., 93., 89., 96., 73.] # 입력 데이터
x2_data = [80., 88., 91., 98., 66.] # 모의고사라 생각 
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.] # 출력 데이터 # 수능점수라 생각

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')


In [3]:
hx=w1*x1 + w2*x2 + w3*x3 + b

In [4]:
cost=tf.reduce_mean( tf.square(hx-Y) ) # square = 제곱

In [5]:
opt=tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [6]:
train=opt.minimize(cost)

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(2001):
    _, cv, hv = sess.run([train, cost, hx],
     feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step%100==0:
        print(step, 'cost:',cv, 'prediction:', hv)
        # 정답 [149.50464 186.11029 179.94537 194.88257 144.90878]

0 cost: 77437.836 prediction: [ -99.19784 -109.40472 -112.99919 -123.97137  -79.7757 ]
100 cost: 9.054449 prediction: [147.81749 187.27113 179.43388 194.47038 146.46773]
200 cost: 8.593814 prediction: [147.92982 187.19392 179.46803 194.49734 146.36446]
300 cost: 8.157446 prediction: [148.0391  187.11874 179.50122 194.5236  146.2639 ]
400 cost: 7.744034 prediction: [148.14546 187.04561 179.5335  194.54922 146.16603]
500 cost: 7.352376 prediction: [148.24895 186.97444 179.56493 194.57422 146.07074]
600 cost: 6.981341 prediction: [148.34964 186.90518 179.59547 194.59857 145.97797]
700 cost: 6.6297913 prediction: [148.44763 186.8378  179.62523 194.62233 145.88763]
800 cost: 6.296774 prediction: [148.54295 186.77222 179.65413 194.64548 145.79968]
900 cost: 5.981287 prediction: [148.63571 186.70842 179.68227 194.66806 145.71407]
1000 cost: 5.6823683 prediction: [148.72597 186.64632 179.70964 194.6901  145.6307 ]
1100 cost: 5.3991776 prediction: [148.8138  186.5859  179.73627 194.71156 145.54

In [9]:
print(sess.run([w1,w2,w3,b]))
# 회귀모델 = 1.4419925 * x1 + 0.20719662 * x2 + 0.33928198 * x3 + 2.2179823

[array([1.4419935], dtype=float32), array([0.20719658], dtype=float32), array([0.33928105], dtype=float32), array([2.2179823], dtype=float32)]


In [ ]:
#2. 다중선형회귀모델

In [15]:
# 5*3
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
# 5*1          
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

# x1 = tf.placeholder(tf.float32)
# x2 = tf.placeholder(tf.float32)
# x3 = tf.placeholder(tf.float32)
X = tf.placeholder(tf.float32, shape=[None, 3]) 
# [5,3] None : 입력 데이터 건수가 정해지지 않음, 텐서플로우가 새어서 값을 정해줘

# Y = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32, shape=[None, 1])

# w1 = tf.Variable(tf.random_normal([1]), name='weight1')
# w2 = tf.Variable(tf.random_normal([1]), name='weight2')
# w3 = tf.Variable(tf.random_normal([1]), name='weight3')
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
# x * w
# [5,3] * [3,1]

b = tf.Variable(tf.random_normal([1]), name='bias')

# hx=w1*x1 + w2*x2 + w3*x3 + b
hx = tf.matmul(X, W) + b

In [16]:
cost = tf.reduce_mean(tf.square(hx - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())


In [17]:
for step in range(2001):
    _, cv, hv= sess.run([train, cost, hx], feed_dict={X:x_data, Y:y_data})
    if step%100==0:
        print(step, cv, hv)

0 46.92759 [[146.40254]
 [177.59459]
 [174.47066]
 [185.3654 ]
 [139.80957]]
100 4.3032517 [[152.21686]
 [184.53568]
 [181.33368]
 [192.84586]
 [145.08647]]
200 4.2578516 [[152.24068]
 [184.51842]
 [181.3398 ]
 [192.8593 ]
 [145.0562 ]]
300 4.2139444 [[152.26372]
 [184.50172]
 [181.3457 ]
 [192.8726 ]
 [145.02661]]
400 4.1715174 [[152.28609]
 [184.48547]
 [181.35138]
 [192.88577]
 [144.99773]]
500 4.1305056 [[152.30774]
 [184.46973]
 [181.35687]
 [192.89874]
 [144.96947]]
600 4.0908313 [[152.32867]
 [184.45445]
 [181.36212]
 [192.9115 ]
 [144.94182]]
700 4.052459 [[152.34903]
 [184.43962]
 [181.36722]
 [192.92413]
 [144.91483]]
800 4.0152617 [[152.3687 ]
 [184.42523]
 [181.37207]
 [192.9366 ]
 [144.88843]]
900 3.9791992 [[152.38773]
 [184.41125]
 [181.37672]
 [192.94888]
 [144.86258]]
1000 3.9442391 [[152.40617]
 [184.39774]
 [181.38124]
 [192.96104]
 [144.83733]]
1100 3.9103112 [[152.42401]
 [184.38458]
 [181.38556]
 [192.97304]
 [144.8126 ]]
1200 3.8773994 [[152.44125]
 [184.37186]
 

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#3. 다중선형회귀모델- 파일

In [38]:
xy=np.loadtxt('f:/data/data-test-score.csv', delimiter=',')
xy

x_data=xy[:,0:-1]
y_data=xy[:,[-1]]

In [39]:


# x1 = tf.placeholder(tf.float32)
# x2 = tf.placeholder(tf.float32)
# x3 = tf.placeholder(tf.float32)
X = tf.placeholder(tf.float32, shape=[None, 3]) 
# [5,3] None : 입력 데이터 건수가 정해지지 않음, 텐서플로우가 새어서 값을 정해줘

# Y = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32, shape=[None, 1])

# w1 = tf.Variable(tf.random_normal([1]), name='weight1')
# w2 = tf.Variable(tf.random_normal([1]), name='weight2')
# w3 = tf.Variable(tf.random_normal([1]), name='weight3')
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
# x * w
# [5,3] * [3,1]

b = tf.Variable(tf.random_normal([1]), name='bias')

# hx=w1*x1 + w2*x2 + w3*x3 + b
hx = tf.matmul(X, W) + b

In [40]:
cost = tf.reduce_mean(tf.square(hx - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())


In [41]:
for step in range(2001):
    _, cv, hv= sess.run([train, cost, hx], feed_dict={X:x_data, Y:y_data})
    if step%100==0:
        print(step, cv, hv)

0 132334.8 [[-179.17189]
 [-229.71855]
 [-218.6358 ]
 [-242.0993 ]
 [-175.42757]
 [-137.06706]
 [-183.03987]
 [-137.83781]
 [-222.84178]
 [-216.4373 ]
 [-176.53632]
 [-181.90602]
 [-222.08168]
 [-179.86816]
 [-186.46063]
 [-235.57068]
 [-170.91832]
 [-218.89906]
 [-208.87569]
 [-186.03853]
 [-215.32906]
 [-218.44655]
 [-202.94348]
 [-171.71896]
 [-233.96988]]
100 109.76625 [[162.27707]
 [181.3614 ]
 [186.03406]
 [198.84122]
 [138.07423]
 [ 94.49177]
 [147.15964]
 [107.12743]
 [161.77579]
 [140.3697 ]
 [141.56906]
 [132.14299]
 [195.78075]
 [167.2235 ]
 [145.38452]
 [181.72885]
 [159.58257]
 [177.3544 ]
 [189.35446]
 [170.24863]
 [171.90143]
 [167.3764 ]
 [166.12787]
 [172.03378]
 [191.853  ]]
200 100.97845 [[161.85869 ]
 [181.51697 ]
 [185.8304  ]
 [198.83446 ]
 [138.17908 ]
 [ 94.977875]
 [147.28966 ]
 [107.393196]
 [162.33672 ]
 [141.4235  ]
 [141.66975 ]
 [132.61528 ]
 [195.36174 ]
 [166.61197 ]
 [145.63728 ]
 [182.03085 ]
 [158.94339 ]
 [177.49365 ]
 [188.81941 ]
 [169.73766 ]
 [17

In [43]:
# 100, 80, 95 수능? 

# 60, 70, 100, 90, 100, 80
sess.run(hx, feed_dict={X:[[100,80, 95]]})

array([[179.00342]], dtype=float32)

In [44]:
sess.run(hx, feed_dict={X:[[60 ,70, 100], [90, 100, 80]]})

array([[149.06021],
       [189.78485]], dtype=float32)

In [ ]:
# 미분을 해서 cost를 낮추는 쪽으로 w와 b를 계속 업데이트 한다.

# entropy는 복잡도를 의미

# 회귀모델 -> 연속형 예측 -> 분류문제 활용하기 위해서 (by sigmoid)
# wx + b -> -inif ~ +inif -> 0 ~ 1 

# Multinoimial Classfication

# softmax function : 값을 확률로 변환해주는 함수

In [48]:
from tqdm import tqdm_notebook

In [54]:
# 단일 분류기 / 다중 분류기

x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

X = tf.placeholder(tf.float32, shape=[None, 2]) #2차원 
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
#  x    *    w
#[6,2]  *  [2,1]
b = tf.Variable(tf.random_normal([1]), name='bias')
#hx= sigmoid(w1*x1 + w2*x2 + b)
hx=tf.sigmoid(tf.matmul(X,W) + b)  # 모델

cost = -tf.reduce_mean((Y*tf.log(hx)+(1-Y)*tf.log(1-hx)))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

pred = tf.cast(hx>0.5, dtype=tf.float32)  # tf.cast : casting 해줌 0.5보다 크면 True, 아니면 False
# dtype을 float으로 해주면 0.5보다 크면 1, 아니면 0
acc = tf.reduce_mean(tf.cast(tf.equal(pred, Y), dtype=tf.float32)) # equal : 같으면 true, 다르면 false

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(10001)):
    cv, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
    if step % 200 ==0:
        print(step, cv)

C:\Users\poeun\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:37: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/10001 [00:00<?, ?it/s]

0 1.2449453
200 0.7689009
400 0.6054919
600 0.5338766
800 0.4948564
1000 0.468637
1200 0.44822812
1400 0.4308571
1600 0.4153067
1800 0.4009966
2000 0.38762936
2200 0.37504056
2400 0.36313155
2600 0.35183707
2800 0.34110996
3000 0.3309122
3200 0.32121164
3400 0.31197938
3600 0.3031889
3800 0.29481512
4000 0.28683475
4200 0.27922568
4400 0.2719669
4600 0.26503852
4800 0.25842196
5000 0.25209957
5200 0.24605471
5400 0.24027176
5600 0.23473608
5800 0.22943391
6000 0.22435226
6200 0.21947885
6400 0.21480256
6600 0.21031256
6800 0.20599884
7000 0.20185201
7200 0.19786327
7400 0.19402455
7600 0.19032788
7800 0.18676609
8000 0.18333232
8200 0.1800202
8400 0.17682369
8600 0.17373723
8800 0.17075533
9000 0.16787313
9200 0.1650859
9400 0.16238914
9600 0.15977879
9800 0.15725091
10000 0.15480159


In [53]:
sess.run(pred, feed_dict={X:x_data, Y:y_data})

array([[0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [55]:
sess.run(acc, feed_dict={X:x_data, Y:y_data})

1.0

In [61]:
# 당뇨병 분류기
xy = np.loadtxt('f:/data/data_diabetes.csv', delimiter=',') # 바로 array 상태로 불러옴
xy.shape # (759, 9)
xy

array([[-0.294118 ,  0.487437 ,  0.180328 , ..., -0.53117  , -0.0333333,
         0.       ],
       [-0.882353 , -0.145729 ,  0.0819672, ..., -0.766866 , -0.666667 ,
         1.       ],
       [-0.0588235,  0.839196 ,  0.0491803, ..., -0.492741 , -0.633333 ,
         0.       ],
       ...,
       [-0.411765 ,  0.21608  ,  0.180328 , ..., -0.857387 , -0.7      ,
         1.       ],
       [-0.882353 ,  0.266332 , -0.0163934, ..., -0.768574 , -0.133333 ,
         0.       ],
       [-0.882353 , -0.0653266,  0.147541 , ..., -0.797609 , -0.933333 ,
         1.       ]])

In [62]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [63]:
y_data.shape

(759, 1)

In [69]:
X = tf.placeholder(tf.float32, shape=[None, 8]) 
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([8, 1]), name='weight')
#  x    *    w
#[8,2]  *  [2,1]
b = tf.Variable(tf.random_normal([1]), name='bias')
#hx= sigmoid(w1*x1 + w2*x2 + ... + w8*x8 + b)
hx=tf.sigmoid(tf.matmul(X,W) + b)

cost = -tf.reduce_mean((Y*tf.log(hx)+(1-Y)*tf.log(1-hx)))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

pred = tf.cast(hx>0.5, dtype=tf.float32)  # tf.cast : casting 해줌 0.5보다 크면 True, 아니면 False
# dtype을 float으로 해주면 0.5보다 크면 1, 아니면 0
acc = tf.reduce_mean(tf.cast(tf.equal(pred, Y), dtype=tf.float32)) # equal : 같으면 true, 다르면 false

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in tqdm_notebook(range(30001)):
    cv, _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data})
    if step % 200 ==0:
        print(step, cv)

C:\Users\poeun\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:22: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`


  0%|          | 0/30001 [00:00<?, ?it/s]

0 0.76693213
200 0.72284657
400 0.697709
600 0.6780375
800 0.6608255
1000 0.6453747
1200 0.63142955
1400 0.6188244
1600 0.60742027
1800 0.5970933
2000 0.5877327
2200 0.5792385
2400 0.5715212
2600 0.56450087
2800 0.5581059
3000 0.5522722
3200 0.54694283
3400 0.542067
3600 0.5375994
3800 0.53349936
4000 0.52973133
4200 0.526263
4400 0.5230658
4600 0.5201141
4800 0.51738524
5000 0.51485884
5200 0.5125166
5400 0.5103423
5600 0.50832117
5800 0.50644004
6000 0.5046872
6200 0.50305176
6400 0.5015242
6600 0.5000959
6800 0.49875882
7000 0.49750596
7200 0.4963307
7400 0.49522725
7600 0.49419007
7800 0.4932144
8000 0.49229586
8200 0.4914302
8400 0.4906137
8600 0.48984295
8800 0.4891148
9000 0.48842633
9200 0.48777497
9400 0.48715812
9600 0.48657355
9800 0.48601928
10000 0.48549342
10200 0.48499396
10400 0.4845194
10600 0.48406824
10800 0.4836389
11000 0.48323017
11200 0.48284093
11400 0.4824698
11600 0.48211586
11800 0.48177812
12000 0.48145565
12200 0.48114753
12400 0.48085302
12600 0.48057133
1

In [70]:
pv, accv = sess.run([pred, acc], feed_dict={X:x_data, Y:y_data})

In [71]:
accv # 정확도 

0.77470356

In [78]:
sess.run(pred, feed_dict={X:[[-0.43, 0.17, 0.2, 0.5, 0.2, -0.33696,
       -0.14962, -0.3]]}) # 이 정보를 가진 사람은 당뇨병일까

array([[1.]], dtype=float32)