In [1]:
import numpy as np

In [4]:
a=np.array([2,1]) #1차원 배열(벡터)
b=np.array([3,2,1])
X=np.array([[2,1,3], [2,1,1]]) #행렬

In [12]:
import tensorflow as tf

In [13]:
tf.__version__

'2.2.0'

In [15]:
# 텐서플로우 1버전 사용하기
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [19]:
sess = tf.Session()

In [17]:
# 텐서플로우는 edges와 nodes로 구조화된 graph로 프로그램이 구성
a=tf.constant(1) # a를 1이라 하자 (지정)
print(a)
with tf.Session() as sess:
    print(a.eval())


Tensor("Const_1:0", shape=(), dtype=int32)
1


In [ ]:
# 텐서플로우는 빌딩구조와 실행구조(session)에 대한 처리 순서
# session : 연산을 수행하기 위한 권한(자격)

In [20]:
a=tf.constant([2,1]) # 1차원 텐서(벡터)
# = 는 할당, 저장의 개념이 아니라 정의, 지정의 개념이다.
a

<tf.Tensor 'Const_2:0' shape=(2,) dtype=int32>

In [21]:
sess.run(a)

array([2, 1])

In [22]:
b=tf.constant([[2,1], [1,3]]) # 2차원 텐서(텐서플로우에서 행렬)
b

<tf.Tensor 'Const_3:0' shape=(2, 2) dtype=int32>

In [24]:
sess.run(b) # 그래프를 실행해라(tensorflow)

array([[2, 1],
       [1, 3]])

In [25]:
import math

In [28]:
a=np.array([3,2]) #a벡터
b=np.array([1,4]) #b벡터

In [29]:
a+b #벡터합

array([4, 6])

In [30]:
a-b # 벡터차

array([ 2, -2])

In [31]:
np.linalg.norm(a) # a벡터 크기
np.linalg.norm(b) # b벡터 크기

3.605551275463989

In [33]:
def mynorm(x):
    return math.sqrt(sum([i**2 for i in x]))
mynorm(a)

3.605551275463989

In [34]:
# 벡터 내적

In [35]:
a=np.array([3,2]) #a벡터
b=np.array([1,4]) #b벡터

In [36]:
a.dot(b) # 3*1 + 2*4 = 11 
# 내적

11

In [37]:
a=np.array([2,1]) #a벡터
b=np.array([-1,2]) #b벡터

In [39]:
np.dot(a,b)

0

In [40]:
X=np.array([[1,2,3], [4,5,6]])  # 2행 3열
Y=np.array([[1,2,3], [4,5,6]])
X+Y

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
X*Y # 요소간 곱셈(행렬의 곱셈이 아님. element-wise product)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [45]:
# X@Y # 행렬의 곱셈(에러 발생)
X # 2,3
Y.T # 2,3 => 3,2

#matrix multiply(행렬의 곱셈)
X@Y.T # 2,3 * 3,2 => 2,2
X.dot(Y.T)

array([[14, 32],
       [32, 77]])

In [ ]:
# AB not equal BA

In [ ]:
# 단위행렬 : 행렬의 대각요소 값이 1, 나머지 원소 값이 0인 행렬 (E, I)
# 전치행렬 : 행과 열을 교환한 행렬 (T)

In [48]:
#역행렬
X=np.array([
    [2,5],
    [1,3]])

np.linalg.inv(X) # X 역행렬

array([[ 3., -5.],
       [-1.,  2.]])

In [49]:
X @ np.linalg.inv(X)

array([[1., 0.],
       [0., 1.]])

In [50]:
X=np.array([[2,3], [-1,4]])
Y=np.array([7,2])

In [52]:
np.linalg.inv(X) @ Y

array([2., 1.])

In [53]:
def myfunc(x):
    return 2*x + 1

In [54]:
myfunc(-2)

-3